name: Pull Request Build

on:
  pull_request:
    branches:
     - main

jobs:
  build:

    # Make sure it builds for LTS versions of Java
    strategy:
      matrix:
        java_version: [8, 11, 17, 21]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: "${{ matrix.java_version }}"
        distribution: "temurin"
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml